# Workflow name
name: Portfolio CI/CD

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main # Or the branch you use for production code

# Define the jobs to be executed
jobs:
  build-and-deploy:
    # Run on the latest Ubuntu environment
    runs-on: ubuntu-latest

    # Steps to be executed in this job
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building multi-platform images (recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root of the repository
          push: true # Push the image to the registry
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-app:latest # Tag the image with your username and app name
          cache-from: type=gha # Use GitHub Actions cache for faster builds
          cache-to: type=gha,mode=max

      # Deploy to DigitalOcean Droplet via SSH
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.0.3 # Use a popular SSH action
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Log in to Docker Hub on the droplet (if required, depends on your setup)
            # docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-app:latest

            # Stop and remove the old container if it's running
            # Use || true to prevent the workflow from failing if the container doesn't exist
            docker stop portfolio-container || true
            docker rm portfolio-container || true

            # Run a new container from the latest image
            # -d: run in detached mode
            # -p 80:80: map droplet's port 80 to container's port 80
            # --name: give the container a name
            # docker run -d -p 80:80 --name portfolio-container ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-app:latest
            docker run -d \
            -p 80:80 \
            -p 443:443 \
            --name portfolio-container \
            -v /etc/letsencrypt/live/jyllandteodosio.dev:/etc/nginx/ssl \
            ${{ secrets.DOCKER_HUB_USERNAME }}/portfolio-app:latest

            # Optional: Clean up old unused Docker images
            # docker image prune -f
